# Generated by Django 4.1.3 on 2024-02-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapi', '0002_creature_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creaturecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creature', to='ccapi.category'),
        ),
        migrations.AlterField(
            model_name='creaturecategory',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ccapi.creature'),
        ),
    ]
